import { useSession } from 'next-auth/react';
import Head from 'next/head';
import Hero from '../components/Hero';
import Service from '../components/Service';

export default function Home() {
  const { data: session } = useSession();

  return (
    <div>
      <Head>
        <title>Dahsboard - Diets App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Service />
    </div>
  );
}
